name: Testing The Project
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Getting the code
        uses: actions/checkout@v4
      - name: Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Installing dependencies
        run: npm ci
      - name: Running all tests
        run: npm test
